### ISSUE TITLE
Enable ping by default

### ISSUE THREAD

**Issue by mradamcox** [healthyregions/SDOHPlace-MetadataManager#17]
Ping should be enabled on new cores when they are created.

This seems to be set by `core-name/data/server-enabled.txt`, but more investigation should be done to figure out how to properly enable it programmatically.

**Comment by mradamcox** [comment]
@pengyin-shan can you look into this? It may be we just need to add `server-enabled.txt` into our conf set up so that it is automatically copied to new cores when they are created with our bash script.

**Comment by pengyin-shan** [comment]
@mradamcox sure! I'll take care of this
